version: '3.9'

services:
  api:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - .:/app
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
